name: Release FreeBSD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-freebsd:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: "x86_64-unknown-freebsd"
          args: "--locked --release"
          strip: true
      - name: Rename library
        run: cp target/x86_64-unknown-freebsd/release/libparinfer_rust.so parinfer-rust-freebsd.so
      - name: Upload libraries to GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: parinfer-rust-freebsd.so
